CoreCRMNorthwindSemantic/ViewComponents/TabsListViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using CoreCRMNorthwindSemantic.Models;
using Microsoft.AspNetCore.Mvc;

namespace CoreCRMNorthwindSemantic.ViewComponents
{
    public class TabsListViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(ClaimsPrincipal user)
        {
            var items = GetUserTabsAsync(user);
            return View(items);
        }
        private UserTabStateModel GetUserTabsAsync(ClaimsPrincipal user)
        {
            TabSettings tabSettings = new TabSettings("Home", "/");
            List<TabSettings> listTabSettngs = new List<TabSettings>();
            listTabSettngs.Add(tabSettings);
            var userTabState = new UserTabStateModel(user, listTabSettngs);
            return userTabState;
        }
    }
}

CoreCRMNorthwindSemantic/Views/Shared/_Layout.cshtml
@using CoreCRMNorthwindSemantic.Models
@using CoreCRMNorthwindSemantic.ViewComponents

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreCRMNorthwindSemantic</title>

    <link rel="stylesheet" href="~/css/semantic.superhero.min.css" />
    <link rel="stylesheet" href="~/css/fontawesome-all.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,300" />
    <script src="~/lib/jquery/dist/jquery.js"></script>

    <environment include="Development">
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link href="~/css/sidebar.css" rel="stylesheet" />
</head>
<body>
    <div class="ui left sidebar visible sticky fixed vertical menu">
        <div id="ccrmns_menu">
            <ul>
                <li class=""><a href="#" target="_blank"><span><i class="fa fa-fw fa-home"></i> Home</span></a></li>
                <li class="active">
                    <a href="#"><span><i class="fa fa-fw fa-bars"></i> Menus</span><span class="cnt">2</span></a>
                    <ul style="display: none;">
                        @* set display block to default to open *@
                        <li class="even"><a href="#"><span>Menu 1.1</span></a></li>
                        <li class="odd"><a href="#"><span>Menu 2</span></a></li>
                    </ul>
                </li>
                <li><a href="#"><span><i class="fa fa-fw fa-cog"></i> Settings</span></a></li>
                <li><a href="#"><span><i class="fa fa-fw fa-phone"></i> Contact</span></a></li>
                <li class="">
                    <a href="#"><span><i class="fa fa-fw fa-bars"></i> Menus</span><span class="cnt">2</span></a>
                    <ul style="display: none;">
                        <li class="even"><a href="#"><span>Menu 1.1</span></a></li>
                        <li class="odd"><a href="#"><span>Menu 2</span></a></li>
                    </ul>
                </li>
                <partial name="_LoginPartial" />

            </ul>
        </div>
    </div>
    <div class="pusher">
        <div class="ui grid">
            <div class="ui two column grid">
                <div class="eight wide column right floated">
                    @await Component.InvokeAsync("TabsList", new { User = User })
                    <!-- Main content !-->
                    <div class="ui container ui raised segment bordered">
                        <div class="ui large breadcrumb">
                            <a class="section">Home</a><i class="right chevron icon divider"></i><a class="section">12345.1.2.ABC</a><i class="right chevron icon divider"></i><div class="active section">Contact Form</div>
                        </div>
                        @RenderBody()
                    </div>
                </div>
                <div class="six wide column right floated">
                    <div class="ui tabular menu">
                        <a class="item active">Contact Form</a><a class="item"> B</a><a class="item"> C</a>
                    </div>
                    <!-- Secondary content !-->
                    <div class=""></div>
                </div>
            </div>
        </div>

        <partial name="_CookieConsentPartial" />

        <div class="container body-content">
            <hr />
            <footer>
                <p>&copy; 2018 - CoreCRMNorthwindSemantic</p>
            </footer>
        </div>
    </div>

    <environment include="Development">
        <script src="~/lib/semantic/dist/semantic.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <script>
        $(document).ready(function () {
            $('.ui.dropdown').dropdown({ on: 'click' });
            $('.ui.progress').progress({ showActivity: false });
            $('.ui.menu a.item').on('click', function () {
                $(this).addClass('active').siblings().removeClass('active');
            });
        });
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>








@*<!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - CoreCRMNorthwindSemantic</title>

        <environment include="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CoreCRMNorthwindSemantic</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>

        <partial name="_CookieConsentPartial" />

        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2018 - CoreCRMNorthwindSemantic</p>
            </footer>
        </div>

        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("Scripts", required: false)
    </body>
    </html>*@